# Generated by Django 5.0.4 on 2024-04-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('GeneralManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormanagement',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctormanagement',
            old_name='doctor_address',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='doctormanagement',
            old_name='doctor_mobile_nmber',
            new_name='speciality',
        ),
        migrations.RenameField(
            model_name='hospitaldetails',
            old_name='hospital_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hospitaldetails',
            old_name='hospital_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctormanagement',
            name='doctor_post',
        ),
        migrations.AddField(
            model_name='doctormanagement',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StaffManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.authuser')),
            ],
        ),
    ]
