# Generated by Django 5.0.4 on 2024-04-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralManagement', '0002_rename_doctor_name_doctormanagement_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalDetails',
            new_name='HospitalDetail',
        ),
    ]
