# Generated by Django 5.0.4 on 2024-04-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralManagement', '0003_rename_hospitaldetails_hospitaldetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffManagement',
        ),
    ]
