# Generated by Django 5.0.4 on 2024-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralManagement', '0004_delete_staffmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormanagement',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
