# Generated by Django 5.0.4 on 2024-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralManagement', '0006_alter_doctormanagement_fee'),
        ('PatientManagement', '0003_alter_patientmanagement_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorManagement',
        ),
    ]
