# Generated by Django 5.0.4 on 2024-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmanagement',
            name='appointment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
