# Generated by Django 5.0.4 on 2024-04-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentManagement', '0002_alter_appointmentmanagement_appointment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentManagement',
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
    ]
