# Generated by Django 5.0.4 on 2024-04-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppointmentManagement', '0003_delete_treatmentmanagement_delete_treatmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(blank=True, max_length=1000, null=True)),
                ('treatment_stauts', models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('ended', 'Ended')], max_length=50)),
                ('treatment_deposit', models.IntegerField(blank=True, null=True)),
                ('treatment_deposit_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('pending', 'Pending'), ('free', 'Free')], max_length=50)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentManagement.appointmentmanagement')),
                ('treatment_cost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TreatmentManagement.treatmentplan')),
            ],
        ),
    ]
