# Generated by Django 5.0.4 on 2024-04-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreatmentManagement', '0002_remove_treatmentmanagement_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentmanagement',
            name='treatment_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
