# Generated by Django 5.0.4 on 2024-04-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreatmentManagement', '0003_treatmentmanagement_treatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentmanagement',
            name='treatment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
