# Generated by Django 5.0.4 on 2024-04-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreatmentManagement', '0004_alter_treatmentmanagement_treatment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentmanagement',
            name='treatment_cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentmanagement',
            name='treatment_deposit',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentmanagement',
            name='treatment_deposit_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('pending', 'Pending'), ('free', 'Free')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='treatmentmanagement',
            name='treatment_stauts',
            field=models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('ended', 'Ended')], default='Pending', max_length=50),
        ),
    ]
