# Generated by Django 5.0.4 on 2024-04-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneralManagement', '0002_rename_doctor_name_doctormanagement_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('aadhar', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeneralManagement.doctormanagement')),
            ],
        ),
    ]
