# Generated by Django 5.0.4 on 2024-04-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorManagement', '0001_initial'),
        ('PatientManagement', '0002_alter_patientmanagement_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmanagement',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DoctorManagement.doctormanagement'),
        ),
    ]
