# Generated by Django 5.0.4 on 2024-05-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0004_patientmanagement_care_off_patientmanagement_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmanagement',
            old_name='care_off',
            new_name='care_of',
        ),
    ]
